[package]
name = "repeated_call_demo"
version = "0.0.1"

[dependencies]
Sui = { local = "/home/wlq/Project/MoveBit/sui/crates/sui-framework/packages/sui-framework" }
[addresses]
repeated_call_demo = "0x0"
